---
- hosts: localhost
  tasks:
       - name: notify block
         debug:
              msg: "this is notify block"
         changed_when: yes
         notify: NOTIFYYYY
  handlers:
      - name: NOTIFYYYY
        debug:
           msg: "this is in handlers..."

# Handlers will only be fired for tasks which report a changed state. 
# In the output of your play you can see the status is ok, which in this case means no new packages have been installed or updated (since state=latest)
